### ISSUE TITLE
local variable 'domain' referenced before assignment

### ISSUE THREAD

**Issue by arbazkiraak** [1N3/BlackWidow#10]
blackwidow -u https://hackerone.com

                _.._
              .'    '.
             /   __   \ 
          ,  |   ><   |  ,
         . \  \      /  / .
          \_'--`(  )'--'_/
            .--'/()'--.
     1N3   /  /` '' `\  \ 
             |        |
              \      /

 + -- --=[https://crowdshield.com
 + -- --=[blackwidow v1.0

[Errno 0] Error
local variable 'domain' referenced before assignment

                _.._
              .'    '.
             /   __   \ 
          ,  |   ><   |  ,
         . \  \      /  / .
          \_'--`(  )'--'_/
            .--'/()'--.
     1N3   /  /` '' `\  \ 
             |        |
              \      /

 + -- --=[https://crowdshield.com
 + -- --=[blackwidow v1.0

[+] URL's Discovered: 
/usr/share/blackwidow/hackerone.com/hackerone.com-urls-sorted.txt
__________________________________________________________________________________________________

[+] Dynamic URL's Discovered: 
/usr/share/blackwidow/hackerone.com/hackerone.com-dynamic-sorted.txt
__________________________________________________________________________________________________

[+] Form URL's Discovered: 
/usr/share/blackwidow/hackerone.com/hackerone.com-forms-sorted.txt
__________________________________________________________________________________________________

[+] Unique Dynamic Parameters Discovered: 
/usr/share/blackwidow/hackerone.com/hackerone.com-dynamic-unique.txt
__________________________________________________________________________________________________

[+] Sub-domains Discovered: 
/usr/share/blackwidow/hackerone.com/hackerone.com-subdomains-sorted.txt
__________________________________________________________________________________________________

[+] Emails Discovered: 
/usr/share/blackwidow/hackerone.com/hackerone.com-emails-sorted.txt
__________________________________________________________________________________________________

[+] Phones Discovered: 
/usr/share/blackwidow/hackerone.com/hackerone.com-phones-sorted.txt
__________________________________________________________________________________________________

[+] Loot Saved To: 
/usr/share/blackwidow/hackerone.com/
__________________________________________________________________________________________________

 HACK THE PLANET!!!!!
**************************************************************************************************
If you haven't already, please donate to this project using the addresses below.
This will help fascilitate improved features and ongoing support.

[+] BTC 1Fav36btfmdrYpCAR65XjKHhxuJJwFyKum
[+] ETH 0x20bB09273702eaBDFbEE9809473Fd04b969a794d
[+] LTC LQ6mPewec3xeLBYMdRP4yzeta6b9urqs2f
[+] XMR 4JUdGzvrMFDWrUUwY3toJATSeNwjn54LkCnKBPRzDuhzi5vSepHfUckJNxRL2gjkNrSqtCoRUrEDAgRwsQvVCjZbS3EN24xprAQ1Z5Sy5s
[+] ZCASH t1fsizsk2cqqJAjRoUmXJSyoVa9utYucXt7

1N3@CrowdShield
https://crowdshield.com
*****************************************************

**Comment by 1N3** [comment]
This is fixed now. May need to git clone the repo and install again to fix.
