### ISSUE TITLE
errors when running in vm

### ISSUE THREAD

**Issue by Gam-7** [1N3/BlackWidow#13]
![2018-05-08 14_33_37-kali-linux-2018 1-vbox-amd64 snapshot 1 running - oracle vm virtualbox](https://user-images.githubusercontent.com/38298059/39760427-2b2aed80-52cd-11e8-8a46-f070e7c46bd9.png)

Linux kali 4.15.0-kali3-amd64 #1 SMP Debian 4.15.17-1kali1 (2018-04-25) x86_64 GNU/Linux

cp blackwidow /usr/bin/blackwidow 
cp injectx.py /usr/bin/injectx.py
pip install -r requirements.txt

Done all 3 of the above without error, any ideas?

**Comment by Gam-7** [comment]
[SOLVED] thanks

**Comment by 1N3** [comment]
👍
