### ISSUE TITLE
add port?

### ISSUE THREAD

**Issue by ifly53e** [1N3/BlackWidow#14]
Does it make sense to add the port for non standard http?  For example:

  parser.add_option('-p', '--port',
      action="store", dest="port",
      help="Port for the URL", default="80")

port = str(options.port)

  if (len(str(domain)) > 4):
    target = "http://" + domain + ":" + port

etc...

**Comment by 1N3** [comment]
yeah, would be helpful. I'll keep this here for consideration.

**Comment by ifly53e** [comment]
You want to give this a look?  Have not tested it yet...Am I on the right track?

https://github.com/ifly53e/BlackWidow/blob/ifly53e-port/blackwidow

**Comment by 1N3** [comment]
hey, looks good so far. If it seems to work for you, let me know and I will push to the main branch when I get a chance.
