### ISSUE TITLE
"blackwidow -d target.com -l 5 -s y - crawl" Command not working

### ISSUE THREAD

**Issue by attacker420** [1N3/BlackWidow#16]
Dear ,

I just start using your tool but while searching content and fuzzing it with OWASP (can be done by your tool with the command i mentioned in Issue title).

```

blackwidow -d target.com -l 5 -s y - crawl


```

Response was containing nothing in .txt directories as made by blackwidow.. Can you please check ..is it working fine on ur end?

**Comment by 1N3** [comment]
Hi, the proper syntax is just 'blackwidow -d target.com -l 5 -s y'. If that doesn't work, try using the -u flag (ie. blackwidow -u https://target.com -l 5 -s y' to see if that works.

**Comment by 1N3** [comment]
Closing out for now but let me know if that doesn't work.

**Comment by attacker420** [comment]
Dear,
As you have written in documentation of tool that "target.com" , User should enter the protocol properly otherwise it will not pick whether the protocol "http" or "https"... It will work for http easily may be but its not working for https. So instead of writing only target.com , i typed https://www.target.com and now it is working fine.


Sincerely,
