### ISSUE TITLE
Some URL come back as "GlobalBadness" instead of the actual URL

### ISSUE THREAD

**Issue by 77697a65** [1N3/BlackWidow#24]
Some URL come back as "GlobalBadness" instead of the actual URL.
Also most of the URLs have incorrect slashes.

Example:

https://www.snapchat.com/ads//partners
globalBadness//blog?regions=north-america
https://www.snapchat.com/ads//

**Comment by 1N3** [comment]
Just pushed the fix for this in the latest version. To apply the fix, please re-clone the repository and re-run the install.sh file. 
```
git clone https://github.com/1N3/BlackWidow
cd BlackWidow
sudo bash install.sh
```
