### ISSUE TITLE
Error opening in kali 2020

### ISSUE THREAD

**Issue by diaverso** [1N3/BlackWidow#27]
Hi, I have an error opening the program with kali 2020.

Code to install it.
pip3 install -r requirements.txt
sudo ./install.sh

Ways to open it 1:
blackwidow
Error:
Traceback (most recent call last):
  File "/usr/bin/blackwidow", line 6, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

Ways to open it 2:
sudo python3 blackwidow
Error:
  File "blackwidow", line 45
    print ""
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("")

Video:
https://www.dropbox.com/s/gom4oyx8yojs17v/0b6a74OYy3.mp4?dl=0

**Comment by ViperTechnologies-RnD** [comment]
same problem as @diaverso 
tried both with python2 and python3

PS. pip is installed for both versions of python

**Comment by 1N3** [comment]
For python2.x, try:
```
sudo pip install BeautifulSoup4
```
For python3:
```
sudo apt-get install python3-bs4
```

**Comment by MDolega20** [comment]
Same errors, 

> 
> 
> For python2.x, try:
> 
> ```
> sudo pip install BeautifulSoup4
> ```
> 
> For python3:
> 
> ```
> sudo apt-get install python3-bs4
> ```

it not helps

**Comment by 1N3** [comment]
Just tested on Kali 2020.2 and it seems to be working for me. I also updated the install.sh file to use python3 to install the dependencies. Can you try re-cloning the repo and running the install.sh again as 'root'?

**Comment by aseelAlsaedi** [comment]
In Ubuntu, I downloaded the last release of blackwidow and I have the same problem as @diaverso have. 
and @1N3 solution not helps

**Comment by 1N3** [comment]
Think I found the issue and have checked in the fix in the master branch for install.sh. To fix, can you try re-cloning the repo and running the install.sh again as 'root'?

```
git clone https://github.com/1N3/BlackWidow
cd BlackWidow
sudo bash install.sh
```

I just tested on a fresh Ubuntu 18.04 image and it appears to be working now.

**Comment by aseelAlsaedi** [comment]
@1N3 the same error appears :(

**Comment by ck9823** [comment]
1 more trai same command

**Comment by ck9823** [comment]
BlackWido any problm install is ubuntu

**Comment by 1N3** [comment]
Can you try running

apt install python-pip python2.7

Then, re-run the install.sh file after? BlackWidow requires python2.x to run, so use python2 /usr/bin/blackwidow to run.

**Comment by 1N3** [comment]
Just pushed the fix for this in the latest version. To apply the fix, please re-clone the repository and re-run the install.sh file. 
```
git clone https://github.com/1N3/BlackWidow
cd BlackWidow
sudo bash install.sh
```
