### ISSUE TITLE
python blackwidow --help does not work

### ISSUE THREAD

**Issue by Lapis420** [1N3/BlackWidow#28]
VMbox - Kali linux

when i type python3 blackwidow this pops up

  File "blackwidow", line 45
    print ""
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("")?

how do i fix?

also when i do ./install.sh and/or sudo ./install.sh i get this error

./install.sh: line 33: pip: command not found

also what is the fix for that?

**Comment by 1N3** [comment]
Can you try running
```
apt install python-pip python2.7
```
Then, re-run the install.sh file after? BlackWidow requires python2.x to run, so use python2 /usr/bin/blackwidow to run.

**Comment by d4nizqy** [comment]
E: Unable to locate package python-pip

**Comment by 1N3** [comment]
Just pushed the fix for this in the latest version. To apply the fix, please re-clone the repository and re-run the install.sh file. 
```
git clone https://github.com/1N3/BlackWidow
cd BlackWidow
sudo bash install.sh
```
