### ISSUE TITLE
error "BeatifulSoup"

### ISSUE THREAD

**Issue by d4nizqy** [1N3/BlackWidow#29]
Traceback (most recent call last):
  File "/usr/bin/blackwidow", line 6, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

im need help with that

**Comment by 1N3** [comment]
Just pushed the fix for this in the latest version. To apply the fix, please re-clone the repository and re-run the install.sh file. 
```
git clone https://github.com/1N3/BlackWidow
cd BlackWidow
sudo bash install.sh
```
