### ISSUE TITLE
RequestsDependencyWarning: urllib3 (1.22) or chardet (2.3.0)

### ISSUE THREAD

**Issue by vishalkrtr** [1N3/BlackWidow#3]
I installed all requirements but I am facing this error.

/home/darklord/.local/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
![black](https://user-images.githubusercontent.com/9496442/34732210-94610a46-f58a-11e7-9618-ab86c2e70d5e.png)

**Comment by 1N3** [comment]
Can you try running the following to see if this works?

```pip install urllib3 --upgrade```

**Comment by vishalkrtr** [comment]
Help me to resolve that.

It is showing some permission error.
I  try > sudo -H pip install urllib3 --upgrade
But it does not resolve  my problem.
![new_black](https://user-images.githubusercontent.com/9496442/34760129-835244ac-f604-11e7-9e11-148ef0c2e083.png)

**Comment by vishalkrtr** [comment]
I resolved the issue by manually deleting all files related to urllib3 and chardet and reinstall these again.

blackwidow working perfectly now.

Thanks

**Comment by 1N3** [comment]
awesome, glad to hear you got it working.
