### ISSUE TITLE
How to solve the 'No such file or directory' and got the results?

### ISSUE THREAD

**Issue by aseelAlsaedi** [1N3/BlackWidow#33]
I ran the BlackWidow  through `sudo bash install.sh` command and got the following:

![Capture](https://user-images.githubusercontent.com/65872828/97627573-9c71dd80-1a3c-11eb-9e40-858488fa781d.PNG)

When I'm using Docker it works well, but I want to work on it locally not by using Docker I don't know why it gives me this error and doesn't save the file. 
@1N3

**Comment by 1N3** [comment]
Are you running blackwidow with sudo/root?

**Comment by aseelAlsaedi** [comment]
yes, I ran with sudo

**Comment by 1N3** [comment]
Which OS and version are you running (ie. Ubuntu 18.04)?

**Comment by aseelAlsaedi** [comment]
Ubuntu 18.04

**Comment by 1N3** [comment]
Not sure what the issue is. I just tried this on an Ubuntu 18.04 image and everything is working fine.

![image](https://user-images.githubusercontent.com/7894221/97639973-ec30b480-19fc-11eb-9264-4dce2025e56b.png)

**Comment by aseelAlsaedi** [comment]
The issue is resolved 👍 
 Thank you for your quick response.
