### ISSUE TITLE
Doesn't crawl, It is generating empty files

### ISSUE THREAD

**Issue by aseelAlsaedi** [1N3/BlackWidow#34]
I am trying to crawl the OWASP Juice-shop application by **BlackWidow**, but it is always generating an empty report (empty files).

**Comment by Juniorn1003** [comment]
Getting the same problem, I tried it on multiple websites and it gets me empty text files.

**Comment by najum98** [comment]
Same at my side

**Comment by 1N3** [comment]
This is probably fixed now but feel free to re-open if still an issue and provide the exact command/site being tested in the bug description.

**Comment by FlexESA** [comment]
same issue - empty files. tried multiple sites
