### ISSUE TITLE
Directory nonexistent

### ISSUE THREAD

**Issue by Blkzer0** [1N3/BlackWidow#4]
Ive installed all the requirements. It looks like theres a problem with the path to the directory.

```
Traceback (most recent call last):
  File "/usr/bin/blackwidow", line 308, in <module>
    urls_saved = open(urls_saved_file,"w+")
IOError: [Errno 2] No such file or directory: '/usr/share/blackwidow//-urls.txt'
sh: 1: cannot create /usr/share/blackwidow//-urls-sorted.txt: Directory nonexistent
sh: 1: cannot create /usr/share/blackwidow//-forms-sorted.txt: Directory nonexistent
sh: 1: cannot create /usr/share/blackwidow//-dynamic-sorted.txt: Directory nonexistent
touch: cannot touch '/usr/share/blackwidow//-dynamic-unique.txt': No such file or directory
cat: /usr/share/blackwidow//-dynamic-sorted.txt: No such file or directory
sh: 1: cannot create /usr/share/blackwidow//-subdomains-sorted.txt: Directory nonexistent
sh: 1: cannot create /usr/share/blackwidow//-emails-sorted.txt: Directory nonexistent
sh: 1: cannot create /usr/share/blackwidow//-phones-sorted.txt: Directory nonexistent

```

**Comment by 1N3** [comment]
Thanks for the heads up! Can you run mkdir -p /usr/share/blackwidow and try again?

**Comment by Blkzer0** [comment]
Thanks 1N3, its working again.

**Comment by 1N3** [comment]
cool, np!

**Comment by cod3x420** [comment]
> 
> 
> Ive installed all the requirements. It looks like theres a problem with the path to the directory.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/blackwidow", line 308, in <module>
>     urls_saved = open(urls_saved_file,"w+")
> IOError: [Errno 2] No such file or directory: '/usr/share/blackwidow//-urls.txt'
> sh: 1: cannot create /usr/share/blackwidow//-urls-sorted.txt: Directory nonexistent
> sh: 1: cannot create /usr/share/blackwidow//-forms-sorted.txt: Directory nonexistent
> sh: 1: cannot create /usr/share/blackwidow//-dynamic-sorted.txt: Directory nonexistent
> touch: cannot touch '/usr/share/blackwidow//-dynamic-unique.txt': No such file or directory
> cat: /usr/share/blackwidow//-dynamic-sorted.txt: No such file or directory
> sh: 1: cannot create /usr/share/blackwidow//-subdomains-sorted.txt: Directory nonexistent
> sh: 1: cannot create /usr/share/blackwidow//-emails-sorted.txt: Directory nonexistent
> sh: 1: cannot create /usr/share/blackwidow//-phones-sorted.txt: Directory nonexistent
> ```

try sudo blackwidow [options]
